[package]
name = "veno-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }

veno-core = { path = "../veno-core" }
clap = { version = "4.0", features = ["derive"] }
